services:
  candidate-gen-service:
    build: ./services/candidate-gen-service/
    image: ${DOCKER_USERNAME}/recsys:candidate-gen-servicev1.0
    ports: 
      - ${CANDIDATE_GEN_SERVICE_PORT}:80
  spring-orchestrator-service:
    build: ./services/orchestrator-service
    image: ${DOCKER_USERNAME}/recsys:spring-orchestrator-servicev1.0
    ports:
      - ${ORCHESTRATOR_SERVICE_PORT}:8080
  spring-ranking-service:
    build: ./services/ranking-service
    image: ${DOCKER_USERNAME}/recsys:spring-ranking-servicev1.0
    ports:
      - ${RANKING_SERVICE_PORT}:8080
  spring-filtering-service:
    build: ./services/filtering-service
    image: ${DOCKER_USERNAME}/recsys:spring-filtering-servicev1.0
    ports:
      - ${FINE_RANKING_SERVICE_PORT}:8080
  feature-store-service:
    build: ./services/feature-store-service
    image: ${DOCKER_USERNAME}/recsys:feature-store-servicev1.0
    ports:
      - ${FEATURE_STORE_SERVICE_PORT}:4000