load('ext://restart_process', 'docker_build_with_restart')

docker_build(
    'ranking-app:v1.0.0',
    dockerfile='../services/ranking/Dockerfile',
    context='..',
    live_update=[
        sync('../services/ranking/src', '/app/src'),
        run(
            'pip install -r /app/requirements.txt',
            trigger=['../services/ranking/requirements.txt']
        )
    ]
)

docker_build_with_restart(
    'orchestrator-app:v1.0.0',
    dockerfile='../services/orchestrator/Dockerfile',
    context='..',
    entrypoint=["java", "org.springframework.boot.loader.launch.JarLauncher"],
    live_update=[
        sync("../services/orchestrator/src", '/app/src'),
    ],
)

docker_build_with_restart(
    'filtering-app:v1.0.0',
    dockerfile='../services/filtering/Dockerfile',
    context='..',
    entrypoint=["java", "org.springframework.boot.loader.launch.JarLauncher"],
    live_update=[
        sync('../services/filtering/src', '/app/src'),
    ],
)

docker_build_with_restart(
    'feature-store-app:v1.0.0',
    dockerfile='../services/feature-store/Dockerfile',
    context='..',
    entrypoint="./server",
    live_update=[
        sync("../services/feature-store/server", "/app/server"),
    ],
)

docker_build_with_restart(
    'candidate-generation-app:v1.0.0',
    dockerfile='../services/candidate-generation/Dockerfile',
    context="..",
    entrypoint="./server",
    live_update=[
        sync("../services/candidate-generation/server", "/app/server"),
    ],
)

k8s_yaml(helm('../infra/helm/charts/candidate-generation', values="../infra/helm/charts/candidate-generation/values-dev.yaml"))
k8s_yaml(helm('../infra/helm/charts/feature-store', values="../infra/helm/charts/feature-store/values-dev.yaml"))
k8s_yaml(helm('../infra/helm/charts/filtering', values="../infra/helm/charts/filtering/values-dev.yaml"))
k8s_yaml(helm('../infra/helm/charts/orchestrator', values="../infra/helm/charts/orchestrator/values-dev.yaml"))
k8s_yaml(helm('../infra/helm/charts/ranking', values="../infra/helm/charts/ranking/values-dev.yaml"))