namespaceOverride: filtering-app
containerPort: 8080
servicePort: 80
environment: production
replicas: 1
deployment:
  enabled: true
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
imageRepository: 963957630095.dkr.ecr.us-west-2.amazonaws.com/recsys/filtering
imageTag: 8bb33b9d652d030ab48fa468d3e648e3a1db697a
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 250m
