syntax = "proto3";

package api.dummy;

// Go
option go_package = "example.com/project/proto/dummy";

// Java
option java_multiple_files = true;
option java_package = "io.grpc.examples.dummy";


// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// The request message containing the user's name.
message HelloRequest {
  string name = 1;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}