apiVersion: v2
name: feature-store
description: A Helm chart for the feature store service
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 0.2.6
    repository: oci://963957630095.dkr.ecr.us-west-2.amazonaws.com/recsys
