imageRepository: 963957630095.dkr.ecr.us-west-2.amazonaws.com/recsys/feature-store
imageTag: 8148872b6d11c2fb67bd451c497db96e6c02322b
resources:
  requests:
    memory: 32Mi
    cpu: 100m
  limits:
    memory: 32Mi
    cpu: 250m
