global:
  environment: production
  servicePort: 80

orchestrator:
  namespaceOverride: orchestrator-app
  containerPort: 8080
  replicas: 2
  deployment:
    enabled: true
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5

candidate-generation:
  namespaceOverride: candidate-generation-app
  containerPort: 80
  replicas: 2
  deployment:
    enabled: true
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5


filtering:
  namespaceOverride: filtering-app
  containerPort: 8080
  replicas: 2
  deployment:
    enabled: true
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5


feature-store:
  namespaceOverride: feature-store-app
  containerPort: 4000
  replicas: 2
  deployment:
    enabled: true
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5


ranking:
  namespaceOverride: ranking-app
  containerPort: 8080
  replicas: 2
  deployment:
    enabled: true
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
