apiVersion: v2
name: candidate-generation
description: A Helm chart for the candidate generation service
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 0.2.13
    repository: "file://../common"
