apiVersion: v2
name: orchestrator
description: A Helm chart for the orchestrator service in the recsys
type: application
version: 0.1.1
appVersion: "1.0.0"
dependencies:
  - name: common
    version: 0.2.13
    repository: "file://../common"
