serviceName: orchestrator-service
namespaceOverride: orchestrator-app
servicePort: 80
containerPort: 8080
environment: production
replicas: 1
ingressClass: alb
ingressPath: /api/recommendations
deployment:
  enabled: true
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
ingressAnnotations:
  alb.ingress.kubernetes.io/scheme: internet-facing
  alb.ingress.kubernetes.io/target-type: ip
  alb.ingress.kubernetes.io/type: external
imageRepository: 963957630095.dkr.ecr.us-west-2.amazonaws.com/recsys/orchestrator
imageTag: 8bb33b9d652d030ab48fa468d3e648e3a1db697a
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 256Mi
    cpu: 250m
