spring.application.name=recsys-orchestrator-service
server.address=0.0.0.0
spring.candidate.gen.container.url=http://candidate-gen-service:80
spring.gbdt.model.container.url=http://gbdt-model-service:80
spring.ltr.model.container.url=http://ltr-model-service:80