name: Build and Push Libary Helm Chart to ECR and Update Umbrella Chart Dependencies

on:
  push:
    branches: ["main"]
    paths:
      - 'infra/helm/charts/common/**'

concurrency: 
  group: umbrella-chart-versioning
  cancel-in-progress: false 

permissions:
  id-token: write 
  contents: write

jobs:
  build-helm-and-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Set up helm
        uses: azure/setup-helm@v4
      
      - name: Update Subcharts and Package Umbrella Chart
        env:
          CHART_VERSION: 0.2.${{ github.run_number }}
        run: |

          yq e -i ".version = \"$CHART_VERSION\"" "infra/helm/charts/common/Chart.yaml"
          
          for dir in infra/helm/charts/*/; do
            if [ "$(basename "$dir")" = "common" ]; then
              echo "Skipping common directory..."
              continue
            fi

            echo "Update Dependency Version for $dir"
            VERSION="$CHART_VERSION" yq e -i '(.dependencies[] | select(.name == "common")).version = env(VERSION)' "$dir/Chart.yaml"
          done

          for dir in infra/helm/charts/*/; do
            if [ "$(basename "$dir")" = "common" ]; then
              echo "Skipping common directory..."
              continue
            fi
            
            echo "Updating dependencies for $dir"
            helm dependency update "./$dir"
          done

      - name: Commit GitOps Update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(helm): update service chart dependencies for new library chart and bump umbrella chart version"
          file_pattern: infra/helm/charts/**
