name: Build and Push Service Images to ECR

on:
  push:
    branches: ["main"]
    paths:
      - 'services/**'

concurrency: 
  group: umbrella-chart-versioning
  cancel-in-progress: false 

permissions:
  id-token: write 
  contents: write

env:
  AWS_REGION: us-west-2
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPO: recsys

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.get-services.outputs.changes }}
    steps:
      - uses: actions/checkout@v5

      - uses: dorny/paths-filter@v4
        id: get-services
        with:
          filters: |
            candidate-generation: 
              - 'services/candidate-generation/**'
            feature-store: 
              - 'services/feature-store/**'
            filtering: 
              - 'services/filtering/**'
            orchestrator: 
              - 'services/orchestrator/**'
            ranking: 
              - 'services/ranking/**'
  build-docker:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        service: ${{ fromJSON(needs.detect-changes.outputs.repos) }}
    steps:
      - uses: actions/checkout@v5

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/Recsys-Github-Actions-ECR-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          cd services/${{ matrix.service }}
          
          docker build -t $REGISTRY/${{ env.ECR_REPO }}/${{ matrix.service }}:${{ github.sha }} .
          docker push $REGISTRY/${{ env.ECR_REPO }}/${{ matrix.service }}:${{ github.sha }} 

  build-helm-and-commit:
    needs: [detect-changes, build-docker]
    if: ${{ fromJSON(needs.detect-changes.outputs.repos) != '[]' && fromJSON(needs.detect-changes.outputs.repos) != '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}

      - name: Configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/Recsys-Github-Actions-ECR-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: Set up helm
        uses: azure/setup-helm@v4
      
      - name: Update Subcharts and Package Umbrella Chart
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          CHANGED_SERVICES: ${{ needs.detect-changes.outputs.repos }}
        run: |
          services=$(echo $CHANGED_SERVICES | jq -r '.[]')

          for service in $services; do
            echo "Update Helm values for: $service"
            yq e -i '.imageTag = "${{ github.sha }}"' "infra/helm/charts/recommendation-engine/charts/$service/values.yaml"
          done

          CURRENT_VERSION=$(yq '.version' infra/helm/charts/recommendation-engine/Chart.yaml)
          
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          
          echo "Bumping Recommendation Engine from $CURRENT_VERSION to $NEW_VERSION"
          
          yq e -i ".version = \"$NEW_VERSION\"" "infra/helm/charts/recommendation-engine/Chart.yaml"

          for dir in infra/helm/charts/recommendation-engine/charts/*/; do
            echo "Updating dependencies for $dir"
            helm dependency update "./$dir"
          done

          aws ecr get-login-password --region ${{ env.AWS_REGION }} | helm registry login --username AWS --password-stdin $REGISTRY

          helm package infra/helm/charts/recommendation-engine --version $NEW_VERSION
          helm push recommendation-engine-$NEW_VERSION.tgz oci://$REGISTRY/${{ env.ECR_REPO }}

      - name: Commit GitOps Update
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(helm): deploy updated services ${{ github.sha }} and bump umbrella chart version"
          file_pattern: infra/helm/charts/recommendation-engine/**
